// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxlgdxtezungbrjgysww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4bGdkeHRlenVuZ2Jyamd5c3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDg4NjAsImV4cCI6MjA3Mjk4NDg2MH0.Gkgb0DPioV88S6J0ntVlx6D2eHC7cHp5i1VG7XjryDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});